### PR TITLE
Transaction element cannot be drawn

### PR DESCRIPTION
**Pull request by qiudaoke**

### CODE REVIEW

**Comment by daisuke-yoshimoto** [comment]
@qiudaoke 
Hi. Thanks for your contribution.
If you can, please add test cases.
https://github.com/Activiti/Activiti/blob/develop/activiti-image-generator/src/test/java/org/activiti/engine/test/image/ProcessDiagramGeneratorTest.java#L96

**Comment by qiudaoke** [comment]
ok, I Add unit test cases .  @daisuke-yoshimoto

**Comment by qiudaoke** [comment]
@balsarori  can you merge this PR。Thanks

**Comment by daisuke-yoshimoto** [comment]
@salaboy @balsarori 
I reviewed this pull request. Is it OK to merge?

I also found another problem. Elements of all subprocesses(Subprocess, Event Subprocess, Transaction Subprocess) are drawn by the same line at present, and are deviated from Spec of BPMN. Is it ok to create another issue on this?

**Comment by salaboy** [comment]
@daisuke-yoshimoto yes.. I will merge this one. Is a great fix from @qiudaoke 
and yes please create a different issue and PR for the other fixes.

**Pull request merged**
