### PR TITLE
Add support for retrieving a VariableInstance and DataObject from the TaskService.

### PR DESCRIPTION
**Pull request by roberthafner**
This support is needed to retrieve localization values for Variables via the TaskService.

### CODE REVIEW

**Comment by tijsrademakers** [comment]
Rob, do you think this is still needed or are the RuntimeService getDataObject methods sufficient?

**Comment by roberthafner** [comment]
Yes, I think the this change balances out the api so that a variable can be retrieved in same formats (name/value, VariableInstance, DataObject) across the RuntimeService or the TaskService.

I plan to update the PullRequest to remove the localization support from the getVariableInstance methods and add the new getDataObject methods. So let’s hold off merging this PR until I include those updates.

thanks!

**Comment by roberthafner** [comment]
Tijs, I've moved the localization support in this Pull Request from the getVariableInstance* methods to the  getDataObject* methods. 

thanks,
Rob

**Comment by roberthafner** [comment]
Tijs, I've updated this Pull Request to also include the changes to support different localization values for DataObjects of the same name as we discussed. 

Thanks,
Rob

**Pull request merged**
