### PR TITLE
design by doing example

### PR DESCRIPTION
**Pull request by gro-mar**

### CODE REVIEW

**Comment by Vadi** [comment]
Hi, @gro-mar - Care to write some documentation on what is this PR all about? I think adding some description and documentation would help others to take this PR forward.

**Comment by martin-grofcik** [comment]
[design by doing article](https://gromar01.wordpress.com/2016/06/16/design-by-doing-with-activiti6/)

**Comment by martin-grofcik** [comment]
[forum discussion](https://forums.activiti.org/content/doing-design)

**Comment by gro-mar** [comment]
Is there any issue with the pull request?

**Comment by tijsrademakers** [comment]
No issue Martin, but it doesn't test new functionality in the Engine. What's your opinion about the reason to add it to the Engine tests?

**Comment by gro-mar** [comment]
the example was moved to the jUnit template project

**Pull request closed without merging**
