### PR TITLE
Fix default flow inactive problem with inclusive Gateway.

### PR DESCRIPTION
**Pull request by daisuke-yoshimoto**
We fixed the problem that default flow's execution with inclusive Gateway isn't active.

### CODE REVIEW

**Comment by jbarrez** [comment]
@daisuke-yoshimoto : what do you mean with 'not active'? Do you mean a default flow isn't taken in an inclusive gateway if no others resolved to a true condition?

**Comment by daisuke-yoshimoto** [comment]
@jbarrez

Thank you for your response.
I'm sorry I didn't make it clear enough. 

Our problem is that is_active_ column of act_ru_executionis is false when default flow execution is reached from inclusive gateway.

Like the following testcase,ExecutionQuery return null, because is_active_ column of act_ru_executionis is false.

```java
public void testDefaultFlowOnly() {
	ProcessInstance processInstance = runtimeService.startProcessInstanceByKey(PROCESS_DEFINITION_KEY);
	Execution execution = runtimeService.createExecutionQuery().processInstanceId(processInstance.getId()).activityId("usertask1").singleResult();
	assertNotNull(execution);
	assertEquals("usertask1", execution.getActivityId());
}
```

### act_ru_executionis record before fix

| act_id_    | is_active_  | is_concurrent_  | is_scope_ | is_event_scope_ |
|:-----------|------------:|:---------------:|:---------:|:---------------:|
| usertask1  | FALSE       |     FALSE       | TRUE      | FALSE           |

### act_ru_executionis record after fix

| act_id_    | is_active_  | is_concurrent_  | is_scope_ | is_event_scope_ |
|:-----------|------------:|:---------------:|:---------:|:---------------:|
| usertask1  | TRUE        |     FALSE       | TRUE      | FALSE           |

**Comment by daisuke-yoshimoto** [comment]
@jbarrez

If possible , please feedback.

**Comment by daisuke-yoshimoto** [comment]
@jbarrez

If possible , please feedback.

**Comment by daisuke-yoshimoto** [comment]
@jbarrez

If possible , please feedback.

**Comment by daisuke-yoshimoto** [comment]
@jbarrez 

Thank you for merging.

**Pull request merged**
