### PR TITLE
Close processEngine after each test in DisabledSchemaValidationTest

### PR DESCRIPTION
**Pull request by lzx404243**
The test `org.activiti.standalone.validation.DisabledSchemaValidationTest.testDisableValidation
` is not idempotent and fails if run twice in the same JVM, because it pollutes state shared among tests. It may be good to clean this state pollution so that some other tests do not fail in the future due to the shared state polluted by this test.

Details
---
When running `DisabledSchemaValidationTest.testDisableValidation` twice, the second run would fail with the following stack trace:
```
org.h2.jdbc.JdbcSQLException: Table "ACT_HI_PROCINST" already exists; SQL statement:
create table ACT_HI_PROCINST ()
at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
at org.h2.message.DbException.get(DbException.java:179)
at org.h2.message.DbException.get(DbException.java:155)
at org.h2.command.ddl.CreateTable.update(CreateTable.java:86)
at org.h2.command.CommandContainer.update(CommandContainer.java:102)
at org.h2.command.Command.executeUpdate(Command.java:261)
at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:233)
at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)
at org.activiti.engine.impl.db.DbSqlSession.executeSchemaResource(DbSqlSession.java:1390)
at org.activiti.engine.impl.db.DbSqlSession.executeSchemaResource(DbSqlSession.java:1299)
at org.activiti.engine.impl.db.DbSqlSession.executeMandatorySchemaResource(DbSqlSession.java:1034)
at org.activiti.engine.impl.db.DbSqlSession.dbSchemaCreateHistory(DbSqlSession.java:1007)
at org.activiti.engine.impl.db.DbSqlSession.dbSchemaCreate(DbSqlSession.java:1002)
at org.activiti.engine.impl.db.DbSqlSession.performSchemaOperationsProcessEngineBuild(DbSqlSession.java:1497)
at org.activiti.engine.impl.SchemaOperationsProcessEngineBuild.execute(SchemaOperationsProcessEngineBuild.java:28)
at org.activiti.engine.impl.interceptor.CommandInvoker$1.run(CommandInvoker.java:37)
at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:78)
at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:57)
at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:42)
at org.activiti.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:48)
at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:63)
at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:29)
at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:44)
at org.activiti.engine.impl.ProcessEngineImpl.<init>(ProcessEngineImpl.java:68)
at org.activiti.engine.impl.cfg.ProcessEngineConfigurationImpl.buildProcessEngine(ProcessEngineConfigurationImpl.java:858)
at org.activiti.standalone.validation.DisabledSchemaValidationTest.setup(DisabledSchemaValidationTest.java:41)
```
The reason for this is that the same `DbSqlSession` is shared between two test runs, and db table `ACT_HI_PROCINST` is already created in the first test run. The fix is to close the process engine in `teardown()` to ensure `DbSqlSession` is cleaned up after each run.

With the proposed fix, the test does not pollute the shared state (and passes when run twice in the same JVM).

### CODE REVIEW

**Comment by lzx404243** [comment]
Can anyone please take a look at this pull request? Any feedback would be appreciated. Thanks!

**Comment by lzx404243** [comment]
@jesty @falko If you get a chance, could you please review this PR? Thanks!

**Review by erdemedeiros — APPROVED** [review]
@lzx404243 thank you for your contribution. LGTM!

**Comment by erdemedeiros** [comment]
@Mergifyio refresh

**Pull request merged**
