### PR TITLE
Fix NPE occured on referring Historic Variable(Serializable Type)

### PR DESCRIPTION
**Pull request by daisuke-yoshimoto**
Fix NullpointerException occured on referring Historic Variable(Serializable Type) #753

TestCase
https://drive.google.com/open?id=0ByO-BAU8ivtKcF80UUFUX0YtVU0

### CODE REVIEW

**Comment by daisuke-yoshimoto** [comment]
I added a test case of activiti-engine project style.
https://github.com/daisuke-yoshimoto/Activiti/commit/427d4ce2904670ce9fb1caeef43fdc025af59a7c

**Comment by daisuke-yoshimoto** [comment]
If possible , please feedback on this pull request.
My correction method or test case was not appropriate?

**Comment by jbarrez** [comment]
@daisuke-yoshimoto :  no problem at all, just the Christmas holidays that caused a bit of a delay in following up pull requests :-)

Thanks for the excellent test case (and finding of the bug). Indeed, the test was perfectly in line with the style of the Activiti code, many thanks!

I did do a small tweak to your fix, see https://github.com/Activiti/Activiti/commit/371fe190f16b6128822201004a21836105249e1f. Instead of doing it in the getPersistentState(), moved it to the query itself (this is the same as done in the HistoricVariableInstanceQueryImpl). Otherwise, if left in the getPersistentState() method, the value of a serializeable value would always be fetched eagerly (which would be different from the original behaviour)

**Comment by daisuke-yoshimoto** [comment]
@jbarrez

Thank you for merging my pull request.

> Instead of doing it in the getPersistentState(), moved it to the query itself (this is the same as done in the HistoricVariableInstanceQueryImpl). Otherwise, if left in the getPersistentState() method, the value of a serializeable value would always be fetched eagerly (which would be different from the original behaviour)

Sorry, My consideration was not enough.
I will take care from the next pull request.

**Pull request merged**
