### PR TITLE
Add the search criteria ProcessInstanceQuery#withException()

### PR DESCRIPTION
**Pull request by daisuke-yoshimoto**
Web added the search criteria(withException) to ProcessInstanceQuery.This criteria get process instances that job failed.

### CODE REVIEW

**Comment by daisuke-yoshimoto** [comment]
If possible , please feedback on this pull request.

**Comment by daisuke-yoshimoto** [comment]
Web consider adding this fix to HistoricProcessInstanceQuery.
If possible , Please feedback on this pull request.

**Comment by jbarrez** [comment]
We haven't got time yet to review this PR. At the moment we're working very hard on Activiti 6, see the https://github.com/Activiti/Activiti/commits/activiti6 branch. We will get to it, don't worry.

**Comment by daisuke-yoshimoto** [comment]
@jbarrez 

Thank you for your reply.

I see your situation.
I'm sorry to rush you .

**Comment by jbarrez** [comment]
No problem, it's good to remind us once in a while. We tend to forget when we're heads down in the code ;-)

**Comment by daisuke-yoshimoto** [comment]
@jbarrez

Web also added the search criteria(withException) to HistoricProcessInstanceQuery.

**Comment by daisuke-yoshimoto** [comment]
@jbarrez

Are you still busy?
If you have a little time, please check this pull request, bacause this diff is simple.

**Comment by jbarrez** [comment]
Merged. Thanks!

Made a small change, renamed withException() to withJobExecption().

**Comment by daisuke-yoshimoto** [comment]
@jbarrez 

Thank you for merging.

**Pull request merged**
