### PR TITLE
Add Escape clause

### LINKED ISSUE #944: Like query parameter cannot escape wildcard characters.
We will escape wildcard characters(%, _) in like query parameter.

But, because Activiti sql don't have escape the ESCAPE clause, we cannot specify escape character.
We must specify the ESCAPE clause in the database like Oracle, SQLServer, DB2.

```xml
<if test="nameLike != null">
  and RES.NAME_ like #{nameLike}
</if>
```

## The target sql file

* https://github.com/Activiti/Activiti/blob/master/modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/Deployment.xml

* https://github.com/Activiti/Activiti/blob/master/modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/Execution.xml

* https://github.com/Activiti/Activiti/blob/master/modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/Group.xml

* https://github.com/Activiti/Activiti/blob/master/modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/HistoricActivityInstance.xml

* https://github.com/Activiti/Activiti/blob/master/modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/HistoricProcessInstance.xml

* https://github.com/Activiti/Activiti/blob/master/modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/HistoricVariableInstance.xml

* https://github.com/Activiti/Activiti/blob/master/modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/Job.xml

* https://github.com/Activiti/Activiti/blob/master/modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/Model.xml

* https://github.com/Activiti/Activiti/blob/master/modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/ProcessDefinition.xml

* https://github.com/Activiti/Activiti/blob/master/modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/Task.xml

* https://github.com/Activiti/Activiti/blob/master/modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/User.xml

### PR DESCRIPTION
**Pull request by daisuke-yoshimoto**
We fixed #944 by adding escape clause.
https://github.com/Activiti/Activiti/issues/944

We selected the escape sequence '\' for compatibility of database that have default escape sequence(like Postgresql).

### CODE REVIEW

**Comment by daisuke-yoshimoto** [comment]
If possible , please feedback on this pull request.

**Comment by daisuke-yoshimoto** [comment]
If possible , please feedback on this pull request.

**Comment by tijsrademakers** [comment]
Does this change work for every supported database in Activiti? MySQL, MSSQL, DB2, Oracle

**Comment by daisuke-yoshimoto** [comment]
We think that this change works for every supported database in Activit, because escape clause is standard specification of SQL.

And, we selected the escape sequence '\' for compatibility of database that have default escape sequence(MySQL, Postgresql).

**Comment by daisuke-yoshimoto** [comment]
@tijsrademakers 
We think that this change works for every supported database in Activit, because escape clause is standard specification of SQL.But, sorry , we don't run the test in MySQL.

And, we selected the escape sequence '\' for compatibility of database that have default escape sequence(MySQL, Postgresql).

**Comment by tijsrademakers** [comment]
I think the escape solution is ok, but it would be nice to make it configurable. So make it work with a variable in the MyBatis XMLs. It would be great if that variable is an empty string by default and that the process engine configuration can be used to enable the escape addition.

**Comment by daisuke-yoshimoto** [comment]
@tijsrademakers

Thank you for your response.

Your proposal is understandable.We will change pull request to be configurable.

**Comment by daisuke-yoshimoto** [comment]
@tijsrademakers

Please review this pull request.

We changed to be configurable.
https://github.com/Activiti/Activiti/pull/979/commits/ac263d089b76a5744634cc2e90e55847d5d2e7b2

We selected the default escape sequence '\' for compatibility of database that have default escape sequence(MySQL, Postgresql).

**Comment by daisuke-yoshimoto** [comment]
@tijsrademakers

If possible , please feedback.

**Comment by tijsrademakers** [comment]
@daisuke-yoshimoto thanks for the changes. Could you make the whole escape '${wildcardEscapeCharacter}' text optional, like we for example do with prefix in ${prefix}ACT_HI_PROCINST ? By default ${prefix} is empty but you can add a prefix if needed. It would be nice if the escape text is empty by default as well and it can be set to escape '\' when needed.

**Comment by daisuke-yoshimoto** [comment]
@tijsrademakers

Thank you for review.

We changed to be optional.
https://github.com/Activiti/Activiti/pull/979/commits/5a12b79a4c3b4700a701ef017754575025465265

**Comment by daisuke-yoshimoto** [comment]
@tijsrademakers

If possible , please feedback.

**Comment by daisuke-yoshimoto** [comment]
@tijsrademakers

If possible , please feedback.

**Comment by jbarrez** [comment]
Thanks! Nice work on the unit tests! 

Did some small changes (see https://github.com/Activiti/Activiti/commit/d1beda2e181fd1e77499674f320bafaadb73288c) to the PR.

**Comment by daisuke-yoshimoto** [comment]
@jbarrez 

Thank you for fix and merging.

**Pull request merged**
