### PR TITLE
IllegalAccessException using the activiti-context.xml file inside a cdi context

### PR DESCRIPTION
**Pull request by flashboss**
I emule a bug using the activiti-context.xml file inside a cdi environmnent. Adding this file in the resources of the application I
have this exception:

Caused by: java.lang.IllegalAccessException: Class
org.activiti.engine.ProcessEngines can not access a member of class
org.activiti.spring.SpringConfigurationHelper with modifiers "public
static"

Infact we cannot use the reflection to call the
SpringConfigurationHelper because the class is protected through the
default access modifier. I see two solutions to resolve this problem:

1 - set to public the org.activiti.spring.SpringConfigurationHelper
class:
    public class SpringConfigurationHelper
    instead of:
    class SpringConfigurationHelper
2 - remove the managing of activiti-context.xml file in the
org.activiti.cdi.impl.ActivitiExtension of the activiti-cdi project so
it doesn't catch the IllegalAccessException

### CODE REVIEW

**Comment by tijsrademakers** [comment]
Hi,

Would it be possible to create a unit test for this issue and make sure that only this unit test is using activiti-context.xml (possibly needs a rename of this file)?

**Comment by flashboss** [comment]
I try.... I could create an alternative src/test/resources repository and move it when the test for activiti-context.xml is started

**Comment by flashboss** [comment]
I've choosen to put the activiti-context.xml because all current tests are executed so the tests are more completed. Otherwise I can start an only new test to test the achievement of the activiti-context.xml file

**Comment by tijsrademakers** [comment]
Changed the SpringConfigurationHelper modifier to public in a separate commit.

**Pull request closed without merging**
