### PR TITLE
ACT-4234 HistoricActivityInstanceQuery search unfinished activities - always zero results

### PR DESCRIPTION
**Pull request by motorina0**
More details here:
https://activiti.atlassian.net/browse/ACT-4234

### CODE REVIEW

**Comment by daisuke-yoshimoto** [comment]
@balsarori @vasiledirla

Are you aware of this pull request?

**Comment by vasiledirla** [comment]
Thanks Vlad for PR.

**Comment by vasiledirla** [comment]
Vlad, it would be nice if you create a PR also for v6 (you should have kudos for this fix also in v6)

**Comment by motorina0** [comment]
Pull Request for v6:
https://github.com/Activiti/Activiti/pull/1073

**Pull request merged**
