### PR TITLE
Add sequenceFlowId in exception message when condition returns null or non-boolean (#1876)

### PR DESCRIPTION
**Pull request by roneigebert**

### CODE REVIEW

**Comment by daisuke-yoshimoto** [comment]
@roneigebert @balsarori 

How about including information on Execution in the exception message?
Since ExecutionEntity.class(the implementation class of DelegateExecution.class) implements toString().

**Comment by roneigebert** [comment]
@balsarori @daisuke-yoshimoto  I do not know muth about Activiti. ExecutionEntity#toString returns the current sequenceFlowId?

Do you want change:
```java
throw new ActivitiException("condition expression returns null (sequenceFlowId: " + sequenceFlowId + ")" );
```
to:
```java
throw new ActivitiException("condition expression returns null (" + execution + ")");
```
?

**Comment by daisuke-yoshimoto** [comment]
@roneigebert @balsarori 
I'm sorry that my explanation was difficult to understand.My request is that we can include the execution information logging in addition to sequenceFlowId.

```java
throw new ActivitiException("condition expression returns null (sequenceFlowId: " + sequenceFlowId + ")" );
```
to:
```java
throw new ActivitiException("condition expression returns null (sequenceFlowId: " + sequenceFlowId + " execution: " + execution + ")" );
```

**Comment by balsarori** [comment]
@daisuke-yoshimoto @roneigebert adding the execution is a good idea.

**Comment by roneigebert** [comment]
@balsarori I added the execution in the message (develop 5.x and 6.x)

**Comment by roneigebert** [comment]
@balsarori how can I use a new 5.X.X version with this code fix? Are you going to deploy this to a new release in maven central (example 5.22.0.X)?

**Comment by balsarori** [comment]
@salaboy any plans for releasing a new 5.x version?

**Comment by salaboy** [comment]
@balsarori that is not my responsibility, you probably know better the release process for 5.x and 6.x so really up to you.

**Pull request merged**
