### PR TITLE
provide MulipartResolver bean for REST API

### PR DESCRIPTION
**Pull request by hoax**
fixes broken multipart file uploads, see issue
https://github.com/Activiti/Activiti/issues/1553

### CODE REVIEW

**Comment by Salaboy** [comment]
@balsarori this looks like a good contribution can we decide if we will merge it or ask for tests agains the changes? This is pointed to the correct branch and besides not having tests the change seems to solve the problem mentioned in the issue linked here.

**Comment by hoax** [comment]
Unfortunately I don't know Spring good enough to be able to write a related test.

**Comment by balsarori** [comment]
I agree. It's a good one indeed, thanks @hoax. Can you set a default max size or maybe just set the max size if the property exists, so that it doesn't  break if property isn't set?

**Comment by hoax** [comment]
set to 1mb as this is the current default in activiti-app.properties

**Comment by Salaboy** [comment]
@hoax thanks a lot for the contribution!
@balsarori please merge this one in 6.x branch.

**Comment by balsarori** [comment]
thanks @hoax

**Pull request merged**
