### PR TITLE
Fix issue 2010

### PR DESCRIPTION
**Pull request by daisuke-yoshimoto**
Fixed the following issue.
https://github.com/Activiti/Activiti/issues/2010

### CODE REVIEW

**Comment by balsarori** [comment]
I don't think it's a good idea to always fetch the values. There could be 100s for variables with unknown  size and fetching could cause issues.

Probably making it optional whether to fetch values would be better (default false).

**Comment by daisuke-yoshimoto** [comment]
@balsarori 
After all it is necessary to fetch to access value.
So if we try to fetch in the command like this fix, it is same performance as fetching in the calling code.

**Comment by balsarori** [comment]
@daisuke-yoshimoto that's true. Old REST API didn't fetch the values and provided a different endpoint for fetching values separately. I don't think it's a good idea to fetch by default and have no other option. 

I would suggest to keep the old behaviour and introduce a new method in RuntimeService that allows fetching variables with there values. Caller can decide which one to use.

**Comment by daisuke-yoshimoto** [comment]
@balsarori 

Thanks. Make sense.

At the moment, this pull request is the fix of bugs of Activiti Engine itself, and secondly to solve the problem of issue 2010 as well. So, I think that this fix itself can be merged.

But, your proposal is not a fix but a spec change, so how about implementing it at the activiti-api layer in the future?
https://github.com/Activiti/activiti-api/blob/develop/activiti-api-process-runtime/src/main/java/org/activiti/api/process/runtime/ProcessRuntime.java

**Comment by balsarori** [comment]
**Note** that variable values could be binary (i.e. a stream of bytes). I don't think we want to always fetch such values.

It makes sense to add this in the API layer and provide a way to fetch the value when it's not of primitive type.

**Comment by daisuke-yoshimoto** [comment]
@balsarori 

> Note that variable values could be binary (i.e. a stream of bytes).

Storing the binary of the large file is not a use case of variables.
First of all, the feature itself to store and retrieve variables via streams will not be provided.

If we need to store the binary of the large file, we should use AttachmentService.
TaskService.createAttachment/getAttachmentContent
https://www.activiti.org/javadocs/org/activiti/engine/taskservice#getAttachmentContent-java.lang.String-
https://www.activiti.org/javadocs/org/activiti/engine/taskservice#createAttachment-java.lang.String-java.lang.String-java.lang.String-java.lang.String-java.lang.String-java.io.InputStream-

> I don't think we want to always fetch such values.

As you say, it is best to fetch binary at the timing when caller trigger getValue method, but it is structurally difficult.
VariableInstance is just a POJO outside the command. So, it is difficult for the Caller to fetch when calling the getValue method outside the command.

In addition, lots of APIs that acquire variables in Activiti Engine have the same behavior as this fix that binary is fetched beforehand in the command. So, I think that as a policy of current revision, this is fine.

For examples.
* https://github.com/Activiti/Activiti/blob/develop/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetExecutionsVariablesCmd.java#L51
* https://github.com/Activiti/Activiti/blob/develop/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetTasksLocalVariablesCmd.java#L52
* https://github.com/Activiti/Activiti/blob/develop/activiti-engine/src/main/java/org/activiti/engine/impl/HistoricVariableInstanceQueryImpl.java#L229
* https://github.com/Activiti/Activiti/blob/develop/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntityImpl.java#L819
* https://github.com/Activiti/Activiti/blob/develop/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/HistoricProcessInstanceEntityImpl.java#L218
* https://github.com/Activiti/Activiti/blob/develop/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/HistoricTaskInstanceEntityImpl.java#L249
* https://github.com/Activiti/Activiti/blob/develop/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/TaskEntityImpl.java#L557
* https://github.com/Activiti/Activiti/blob/develop/activiti-engine/src/main/java/org/activiti/engine/impl/ProcessInstanceHistoryLogQueryImpl.java#L117

**Comment by balsarori** [comment]
@daisuke-yoshimoto 
my point is that caller should have an option whether or not to fetch values from external table (in case they aren't primitive type). 

It might be that the caller isn't interested in fetching the values and is only interested in knowing basic variables information (i.e. name, type, taskId, process instance id, etc! which is what differentiates ```RuntimeService.getVariables``` from ```RuntimeService.getVariableInstances```) of the variables.

This is a valid use case where only variables info are listed and values are fetched as needed.

**Comment by daisuke-yoshimoto** [comment]
@balsarori 
I understand your point, but your proposal is function addition.
This pr is only fixing existing bugs like other parts.

* https://github.com/Activiti/Activiti/blob/develop/activiti-engine/src/main/java/org/activiti/engine/impl/ProcessInstanceHistoryLogQueryImpl.java#L117
* https://github.com/Activiti/Activiti/blob/develop/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetExecutionsVariablesCmd.java#L51
* https://github.com/Activiti/Activiti/blob/develop/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetTasksLocalVariablesCmd.java#L52
* https://github.com/Activiti/Activiti/blob/develop/activiti-engine/src/main/java/org/activiti/engine/impl/HistoricVariableInstanceQueryImpl.java#L229

**Comment by balsarori** [comment]
@daisuke-yoshimoto 
Here there is an option to not initialize variable values i.e.  
https://github.com/Activiti/Activiti/blob/develop/activiti-engine/src/main/java/org/activiti/engine/impl/HistoricVariableInstanceQueryImpl.java#L224

GetExecutionsVariablesCmd and GetTasksLocalVariablesCmd (called by ``` RuntimeService.getVariables``` and ```taskService.getVariables```) are used to fetch the variable values so it's normal to always fetch the values.

ProcessInstanceHistoryLogQueryImpl.java doesn't have an option to fetch values but including the vars is optional.

**Comment by balsarori** [comment]
@daisuke-yoshimoto 
I'd rather have a different method instead of overloading the existing one i.e. ```getInitializedVariableInstances``` but for the command you can add a boolean to determine whether or not to initialize the values.

**Comment by daisuke-yoshimoto** [comment]
@balsarori 
I will add flag excludeVariableInitialization like HistoricVariableInstanceQuery. So, in default mode, query fetch serializable variables. If only explicitly excludeVariableInitialization is true, query don't fetch serializable variables.

**Comment by balsarori** [comment]
@daisuke-yoshimoto 
I had a quick discussion about this with @salaboy and we think we shouldn't change the default behaviour. It's better to introduce a new method i.e. ```getInitializedVariableInstances``` which initializes the values. You can still use the same ```GetExecutionVariableInstancesCmd``` with a boolean that determines whether or not to fetch values (by default doesn't fetch values).

**Comment by daisuke-yoshimoto** [comment]
@balsarori @salaboy 

Ok. So, I will fix as the following as follows.

1. Add getInitializedVariableInstances to RuntimeService
-> add flag to GetExecutionVariableInstancesCmd

2. Add flag to ProcessRuntime.variables
-> Add flag to GetVariablesPayload
https://github.com/Activiti/activiti-api/blob/develop/activiti-api-process-model/src/main/java/org/activiti/api/process/model/payloads/GetVariablesPayload.java

**Comment by daisuke-yoshimoto** [comment]
@balsarori @salaboy 

Well, after all, I tried reconsidering, but I cannot understand the behavior of not initializing object variables(fetching object variables) by default. By default , initializing object variables(fetching object variables) should executed in commands. Optionally Operations that are not  initialized(fetced) should be provided.

### Performance

* I think that performance concerns are not so much even in the operation of fetching by default.
* Since the part that I fixed in this pr is an API that individually specifies the taskId or executionId, it is assumed that there are not so many variables. If the number of variables is not large, there should be not much overhead at the time of fetching.

### Consistency with other parts

* Lots of APIs that acquire variables in Activiti Engine have the same behavior as this fix that binary is fetched beforehand in the command. So, I think that as a policy of current revision, this is fine.

* Also, for HistoricVariableInstanceQuery which you presented, the option is false by default. By default, HistoricVariableInstanceQuery fetch object variables in command.
  * https://github.com/Activiti/Activiti/blob/develop/activiti-engine/src/main/java/org/activiti/engine/history/HistoricVariableInstanceQuery.java#L56

**Comment by salaboy** [comment]
@daisuke-yoshimoto you are right, this is really important.. I will review this now.. 
I'm trying to understand what was the decision at the end.. if we are going to fetch serialised variables by default or not.

**Comment by daisuke-yoshimoto** [comment]
@salaboy 
I summarized. 
https://github.com/Activiti/Activiti/issues/2010#issuecomment-430327242

**Comment by daisuke-yoshimoto** [comment]
@salaboy 
Any updates?

**Comment by daisuke-yoshimoto** [comment]
@salaboy Thanks.

**Pull request merged**
