### PR TITLE
Fix resource loading.

### PR DESCRIPTION
**Pull request by cheleb**
At least in an OSGi environnement this commit fixes the loading of diagram images (userTask, scripTask ... )

### CODE REVIEW

**Comment by tijsrademakers** [comment]
Would it be possible to add a unit test in the activiti-osgi module that's currently failing?

**Comment by cheleb** [comment]
Yep I will try tout do this tonight.

√olivier/mobile
Le 2 févr. 2015 09:19, "Tijs Rademakers" <notifications@github.com> a écrit
:

**Comment by tijsrademakers** [comment]
Did you had a chance to look into the writing the unit test?

**Comment by cheleb** [comment]
Nope ...
I was quite busy those last days ... Nursery :D

√olivier/mobile
Le 13 févr. 2015 08:26, "Tijs Rademakers" <notifications@github.com> a
écrit :

**Comment by cheleb** [comment]
AFAIK it not easy to illustrate in an Unit test.
Could you take a look at my project:  
https://github.com/cheleb/wisdom-activiti/tree/develop 
mvn clean install
cd wisdom-activiti-sample
mvn clean wisdom:run

===> OK

I've pushed a branch https://github.com/cheleb/wisdom-activiti/tree/activii-bug-485 to illustrate this issue, in this branch I've just commented out my patch (OSGi fragment )
mvn clean install
cd wisdom-activiti-sample
mvn clean wisdom:run

====> ERROR

**Comment by tijsrademakers** [comment]
In the example provided I see the icons package getting exported in the pom.xml. And that's a different solution than the one implemented in this pull request. Or did I overlook something?

**Comment by cheleb** [comment]
I'm very sorry, you are right the second (last) solution with the fragment (exporting icons) was enough to fix my issue.

**Comment by tijsrademakers** [comment]
org.activiti.icons is exported in the activiti-image-generator module. Please let us know if this doesn't work.

**Pull request closed without merging**
