### PR TITLE
fix Chinese Disorderly Code when import/edit/deploy model .#818

### PR DESCRIPTION
**Pull request by MicyToy**
fix Chinese Disorderly Code when import/edit/deploy model #818  .Based on **5.21.0-release**

reslove import/edit messy-code
add configuration in `activiti-custom-context.xml` under `processEngineConfiguration`

`<property name="activityFontName" value="\u5fae\u8f6f\u96c5\u9ed1" />
<property name="labelFontName" value="\u5fae\u8f6f\u96c5\u9ed1"/>`

### CODE REVIEW

**Comment by balsarori** [comment]
Are the changes to activiti-custom-context.xml file needed?

**Comment by MicyToy** [comment]
changes in `activiti-custom-context.xml` set activity default font that support chinese charactors, or others.
it resolves CDC when editing with `activiti-moduler`. 

`\u5fae\u8f6f\u96c5\u9ed1` is `Microsoft YaHei` in chinese.

**Comment by balsarori** [comment]
ok can you add a comment in ```activiti-custom-context.xml``` so that users interested in Chinese can use it? That font might not be available in all machines.

**Comment by MicyToy** [comment]
ok. I will do it later. tks.

**Comment by Salaboy** [comment]
@MicyToy this seems to be useful the PR needs to be rebased to 6.x branch. I will close this PR, but please submit another one to point to 6.x branch instead of master.

**Comment by MicyToy** [comment]
Get it. I will refix it on the HEAD of 5.x and 6.x. Later I will create a PR.
Thx.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Salaboy** [comment]
@balsarori can you please follow this one?

**Pull request closed without merging**
