### PR TITLE
Remove trailing semicolons from oracle bulk insert queries

### PR DESCRIPTION
**Pull request by reva**
See https://github.com/Activiti/Activiti/issues/642

### CODE REVIEW

**Comment by reva** [comment]
Another change for the same initial commit. Info log level was to high for these logging statements.

**Comment by jbarrez** [comment]
That too will be merged later on. To see what we still need to merge: https://github.com/Activiti/Activiti/compare/activiti6...master

**Comment by reva** [comment]
Sorry, thought I hadn't seen it on master. Closing request.

**Comment by jbarrez** [comment]
No problem at all! I am glad someone is keeping an eye on the code!

**Pull request closed without merging**
