### PR TITLE
Removed alias table name from the Oracle DB script

### PR DESCRIPTION
**Pull request by moberoi2**
I created this PR to remove Alias table name from the Oracle DB script as it was creating problem. So did changes in Oracle DB script. It solves https://github.com/Activiti/Activiti/issues/4328

### CODE REVIEW

**Comment by eromano** [comment]
can we add some description on why we do so in the body of the PR?

**Comment by balsarori** [comment]
fixes: https://github.com/Activiti/Activiti/issues/4328
@moberoi2 please add description and sign CLA

**Comment by moberoi2** [comment]
> fixes: #4328 @moberoi2 please add description and sign CLA

done

**Comment by moberoi2** [comment]
> can we add some description on why we do so in the body of the PR?

Added description in the body of the PR

**Review by balsarori — APPROVED** [review]

**Pull request merged**
