### PR TITLE
Refactor Spring Boot RestApiAutoConfiguration.SecurityConfiguration…

### PR DESCRIPTION
**Pull request by vpavic**
…to use IdentityServiceUserDetailsService

### CODE REVIEW

**Comment by tijsrademakers** [comment]
Can you explain a bit more what the purpose of this change is?

**Comment by vpavic** [comment]
Hi Tijs,

This pull request is a proposed solution for [ACT-4074](https://activiti.atlassian.net/browse/ACT-4074) - I hope the description on this JIRA ticket clarifies the motivation behind the change.

**Comment by vpavic** [comment]
@tijsrademakers, any comments on this improvement, either here or on [ACT-4074](https://activiti.atlassian.net/browse/ACT-4074)?

**Comment by vpavic** [comment]
Closing in favor of #762.

**Pull request closed without merging**
