### PR TITLE
Fix for ACT-2236

### PR DESCRIPTION
**Pull request by gdharley**

### CODE REVIEW

**Comment by tijsrademakers** [comment]
Hi Greg, I don't understand the change in BoundaryEventJsonConverter. The PROPERTY_CANCEL_ACTIVITY property is already set, so what does this change?

**Comment by gdharley** [comment]
Hi Tijs,

The property is not set when you import a bpmn file into Activiti Explorer.
Release is 5.17.
Create a BPMN file in Eclipse modeler
Import into Activiti Explorer
Deploy immediately

The  CancelActivitiy flag is not promoted.
The change explicitly sets the flag.

**Comment by tijsrademakers** [comment]
Ah ok, this was already fixed at the end of February, so it should already work on master.

**Comment by gdharley** [comment]
Thanks Tijs, I missed that commit (would have saved me a lot of time :-) 
I am also chasing a namespace issue where the target namespace is overwritten (means reports cannot be created). Is this also already fixed?

**Pull request closed without merging**
