### PR TITLE
implement likeIgnoreCase variable query operation in REST api

### PR DESCRIPTION
**Pull request by jtulley**

### CODE REVIEW

**Comment by balsarori** [comment]
@jtulley thanks for the PR,  will be great to apply that to process variables as well.

**Comment by jtulley** [comment]
@balsarori -- I could quickly do that there as well.

**Comment by jtulley** [comment]
Not ready to go yet.  There is a test failure.

**Comment by jtulley** [comment]
@balsarori ready to go.  I added it to querying process variables on a process instance, and process variables in the task.

**Comment by vasiledirla** [comment]
@jtulley will be nice if you would like to prepare a PR also for v6.
Thanks for your contributions.

**Pull request merged**
