### PR TITLE
[WIP] Auto deploy processes from zip files

### PR DESCRIPTION
**Pull request by erdemedeiros**
Added the zip extension so process can be imported from there

### CODE REVIEW

**Comment by erdemedeiros** [comment]
Refers to https://github.com/Activiti/Activiti/issues/2001

**Comment by balsarori** [comment]
@erdemedeiros Note that engine will deploy anything inside the zip file including any non BPMN XML files which I don't think thats something you want.

**Comment by daisuke-yoshimoto** [comment]
@balsarori @erdemedeiros 
Looking at the original issue seems to assume that he wants to deploy files other than bpmn.
https://github.com/Activiti/Activiti/issues/2001

Rather, it may be good to check the integrity of json referenced by bpmn and bpmn by using custom Deployer. https://github.com/Activiti/Activiti/blob/develop/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/deploy/Deployer.java

**Comment by erdemedeiros** [comment]
Thanks @balsarori I'll modify that.

**Comment by erdemedeiros** [comment]
@daisuke-yoshimoto the zip file will contain other files in addition to processes files, but I'm not sure that we are going to use the deployer for that. I'll take a look.

**Comment by erdemedeiros** [comment]
Closing this PR as the strategy has changed. Replaced by https://github.com/Activiti/Activiti/pull/2067

**Pull request closed without merging**
