### PR TITLE
Fix the NPE in isBulkInsertable() by changing .get() to .containsKey()

### PR DESCRIPTION
**Pull request by mittalabhi2123**
For Jira: https://activiti.atlassian.net/browse/ACT-4079

### CODE REVIEW

**Comment by jbarrez** [comment]
The get() was indeed not assuming custom entities, thanks for that fix. It still needs to be there though (eg for Oracle who can't handle eventLogEntity). Added it back here (after the containsKey()): https://github.com/Activiti/Activiti/commit/e7a8bf9ffa42a743e0f359794a0c78e20fe291a9

**Comment by mittalabhi2123** [comment]
Hello Joram,

I am afraid this change will also fail for Custom Entities not in Map. It
will again try to implicit cast null to boolean, and will throw NPE.
I tested it, at my end using following code and it failed:


On Mon, Oct 19, 2015 at 1:01 PM, Joram Barrez <notifications@github.com>
wrote:

> The get() was indeed not assuming custom entities, thanks for that fix. It
> still needs to be there though (eg for Oracle who can't handle
> eventLogEntity). Added it back here (after the containsKey()): e7a8bf9
> <https://github.com/Activiti/Activiti/commit/e7a8bf9ffa42a743e0f359794a0c78e20fe291a9>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Activiti/Activiti/pull/691#issuecomment-149126996>.
>



-- 


*RegardsAbhishek Mittal+919873670980*

**Comment by mittalabhi2123** [comment]
Hello Joram,

I am afraid this change will also fail for Custom Entities not in Map. It
will again try to implicit cast null to boolean, and will throw NPE.
I tested it, at my end using following code and it failed:


>
>
>
>
>
>
>
> *import java.util.HashMap;import java.util.Map;public class Test {  public
> static void main(String args[]) {    Map<String, Boolean> map = new
> HashMap<>();    boolean flag = (map.get("test") == true);
> System.out.println(flag);   }}*


On Mon, Oct 19, 2015 at 10:59 PM, Abhishek Mittal <mittalabhi86@gmail.com>
wrote:

> Hello Joram,
>
> I am afraid this change will also fail for Custom Entities not in Map. It
> will again try to implicit cast null to boolean, and will throw NPE.
> I tested it, at my end using following code and it failed:
>
>
> On Mon, Oct 19, 2015 at 1:01 PM, Joram Barrez <notifications@github.com>
> wrote:
>
>> The get() was indeed not assuming custom entities, thanks for that fix.
>> It still needs to be there though (eg for Oracle who can't handle
>> eventLogEntity). Added it back here (after the containsKey()): e7a8bf9
>> <https://github.com/Activiti/Activiti/commit/e7a8bf9ffa42a743e0f359794a0c78e20fe291a9>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Activiti/Activiti/pull/691#issuecomment-149126996>.
>>
>
>
>
> --
>
>
> *RegardsAbhishek Mittal+919873670980 <%2B919873670980>*
>



-- 


*RegardsAbhishek Mittal+919873670980*

**Comment by jbarrez** [comment]
@mittalabhi2123 : the containsKey() shortcuts the if when it returns false, hence the get() will never be executed.

In your code example, change the second line to 

boolean flag = (map.containsKey("test") && map.get("test") == true);

It now will return false.

**Comment by mittalabhi2123** [comment]
Yes, Sorry, I missed the containsKey() part.

On Mon, Oct 19, 2015 at 11:04 PM, Joram Barrez <notifications@github.com>
wrote:

> @mittalabhi2123 <https://github.com/mittalabhi2123> : the containsKey()
> shortcuts the if when it returns false, hence the get() will never be
> executed.
>
> In your code example, change the second line to
>
> boolean flag = (map.containsKey("test") && map.get("test") == true);
>
> It now will return false.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Activiti/Activiti/pull/691#issuecomment-149291136>.
>



-- 


*RegardsAbhishek Mittal+919873670980*

**Comment by jbarrez** [comment]
No worries, I'm very happy many eyes are seeing the code!

**Pull request merged**
