### PR TITLE
Fix issue 1902

### PR DESCRIPTION
**Pull request by daisuke-yoshimoto**

### CODE REVIEW

**Comment by Salaboy** [comment]
@daisuke-yoshimoto Looking at the code it looks fine to me. I'm not sure if we can validate that this fix is not going to break some other scenarios, but I will delegate to @balsarori the final review because this is 6.x related. In 7 we shouldn't be looking at the Job Executor at all.

**Comment by daisuke-yoshimoto** [comment]
@Salaboy @balsarori 
Beta 1 release of Activiti 7 has also been completed. Do you have time?
If possible, can you review and merge this pull request?

**Comment by balsarori** [comment]
@daisuke-yoshimoto sorry for not responding on this PR. I'm not sure whats the impact of these changes. I'll try to have a look on this today.

**Comment by Salaboy** [comment]
@balsarori if you can review this.. it will be great

**Pull request merged**
