### PR TITLE
Fix(develop)/flow element map

### LINKED ISSUE #1518: Models converted by BpmnJsonConverter have validation errors in activiti 6+, if they contain subprocess
# Problem:
If you convert a `BpmnModel` to json, and it contains subprocesses, validation errors will be reported for links inside subProcesses:

# Root of the problem:
In activiti 6, `Process#getFlowElement` doesn't recursively search for element. Instead, it looks up `flowElementMap` field, which is obviously added in 6.x for performance optimizations and is meant to serve as an **id to element** map in *flow element containers* (Process and SubProcess).

In `addFlowElement` of `SubProcess`, it checks if it's inside another container and adds the currently adding element to `flowElementMap` of that parent container:

[SubProcess.java#L50]:(https://github.com/Activiti/Activiti/blob/b6aba7e29ce1e1c613176c551c04427c9111e942/modules/activiti-bpmn-model/src/main/java/org/activiti/bpmn/model/SubProcess.java#L50)
```java
if (getParentContainer() != null) {
    getParentContainer().addFlowElementToMap(element);
}
```
There is a problem though. If elements are added to some subprocess, before subprocess is added to its parent, the added elements will be missed in parent flowElementMap. Interestingly, this is the case for BpmnJsonConverter. It actually first adds all child flow elements of the subProcess to it, and then adds subprocess itself to its parent.

I think the `addFlowElement` of containers, should also check if the added element is a container itself, and add all entries of it's `flowElementMap` to its own `flowElementMap`.

I can craft a PR to fix this if you want.

### PR DESCRIPTION
**Pull request by alirezamirian**
fixes #1518 (target: `develop`)

### CODE REVIEW

**Comment by Salaboy** [comment]
@alirezamirian this is a great contribution. We will review this and try to merge as soon as possible. 
Can you please check your coding style in your IDE. Codacy is complaining about your indentation policy: https://www.codacy.com/app/Activiti/Activiti/pullRequest?prid=1140196

**Comment by Salaboy** [comment]
@alirezamirian by the way, it will be great if you drop us a message in our gitter channel to have a chat about your contributions: https://gitter.im/Activiti/Activiti7?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by alirezamirian** [comment]
@Salaboy Thanks. Can you please tell me which is the correct indentation? Cause I saw the current code is indented with two spaces and configured my IDEA that way. But codelyzer seems not happy with two space indentation.

**Comment by Salaboy** [comment]
@alirezamirian sure, our IDEs configuration files are here: https://github.com/Activiti/activiti-build/tree/develop/ide-configuration

All the source code that we touch needs to follow those configurations.

**Comment by Salaboy** [comment]
@alirezamirian ok this is ready to be merged. There is one more comment in Codacy, but I will fix it while merging. This should be included in our January Early Access Release.

**Comment by alirezamirian** [comment]
@Salaboy Great. Thank you.

**Pull request merged**
