### PR TITLE
Improving performance of queries by adding indexes.

### PR DESCRIPTION
**Pull request by daisuke-yoshimoto**
We added indexes for improving performance of queries.

## Case1. Many variables exist.

This index is effective in HistoricVariableInstanceQuery#executionId or HistoricVariableInstanceQuery#executionIds.
Bacause SQL Server doesn't use this index, we added table hint to use this index for SQL Server.

```
create index ACT_IDX_HI_PROCVAR_EXEC_ID on ACT_HI_VARINST(EXECUTION_ID_);
```

## Case2. Many history tasks exist.

This index is effective in HistoricTaskInstanceQuery#taskAssignee.

```
create index ACT_IDX_HI_TASK_INST_ASSIGNEE on ACT_HI_TASKINST(ASSIGNEE_);
```

## Case3. Many binary variables exist.

This index already was added to only Oracle, Postgresql.
Because this index is also effective in other databases, we added to other databases.

```
create index ACT_IDX_BYTEAR_DEPL on ACT_GE_BYTEARRAY(DEPLOYMENT_ID_);
```

### CODE REVIEW

**Comment by daisuke-yoshimoto** [comment]
@balsarori
If possible , please feedback.

**Comment by daisuke-yoshimoto** [comment]
@balsarori 
If possible , please feedback.

**Comment by balsarori** [comment]
@daisuke-yoshimoto Sorry for the delayed reply

For historic tables, we try to add as less indices as possible. We'd like to give users the option to determine what's best for them. I agree with Case 3, it will be good to have the same index created for other databases as well.

**Comment by daisuke-yoshimoto** [comment]
@balsarori

Thank you for your reply.
We understood the index policy of Activiti.

We cancel this pull request.

**Pull request closed without merging**
