### PR TITLE
support for CancelEndEvent in angularJS modeler

### PR DESCRIPTION
**Pull request by esahekmat**
add TerminateEndEvent(EndCancelEvent) to the designer

### CODE REVIEW

**Comment by tijsrademakers** [comment]
Thanks for the pull request, but I see some confusion between the cancel and terminate end event. What you implemented in the modeler is a cancel end event and not a terminate end event. The doc changes are also not valid, because it's correctly referring to cancel end events.

**Comment by esahekmat** [comment]
are terminate end event and cancel end event seperate elements?

**Comment by esahekmat** [comment]
I revert doc changes, and also correct my mistake, now it's just implementing cancel end event

**Comment by esahekmat** [comment]
did you see my revise?

**Pull request merged**
