### PR TITLE
exclude jcl over slf4j

### PR DESCRIPTION
**Pull request by martin-grofcik**

### CODE REVIEW

**Comment by jbarrez** [comment]
@martin-grofcik : what's the reasoning for this? I believe this was needed for Spring. 
With jcl excluded, wouldn't this mean the initial bootup logs will be gone, too?

**Comment by martin-grofcik** [comment]
Library should not have runtime dependency on jcl-over-slf4j jar.
I can add jcl-over-slf4j to spring examples - next commits.

**Comment by tijsrademakers** [comment]
Hi Martin, we would like to keep the dependency in, because Spring still uses JCL.

**Comment by martin-grofcik** [comment]
Hi Tijs,

I run mvn dependency:tree in the activiti-spring module. I found only test jcl-over-slf4j dependency there.

**Comment by tijsrademakers** [comment]
Hi Martin, true but Spring still uses JCL. If there's a Log4j dependency that will be used for the JCL logging. So the SLF4j dependency is just there to make sure all our logging using SLF4j.

**Pull request closed without merging**
