### PR TITLE
ACT-4316 set user task end time when it is completed

### PR DESCRIPTION
**Pull request by cristianflorescu**

### CODE REVIEW

**Comment by daisuke-yoshimoto** [comment]
@balsarori 
Are you still under review?

**Comment by balsarori** [comment]
Yes I'm doing a final review.

**Comment by daisuke-yoshimoto** [comment]
@balsarori 
Thanks for your review.
Do you still need the following branche?
https://github.com/Activiti/Activiti/tree/ACT-4316-boundary-event

**Comment by balsarori** [comment]
Nope, I've deleted it. Thanks :)

**Pull request merged**
