### PR TITLE
[WIP] Import processes from application zip file

### PR DESCRIPTION
**Pull request by erdemedeiros**
First draft, do not merge yet.

### CODE REVIEW

**Comment by erdemedeiros** [comment]
Refers to https://github.com/Activiti/Activiti/issues/2047

**Comment by salaboy** [comment]
@erdemedeiros this is really good.. basically what I was expecting for an initial iteration. 
The only thing that I will notice here is that based on our latest refactorings we should move activiti-applications to activiti-core-common and rename it to activiti-spring-applications (due its dependency on autoconfigurations and spring annotations). Also, is there a class that represent the Application itself? 

In the same way as connectors, when we read an application from /src/main/resources/applications/ we should have a Bean, called ApplicationsService which collects the names of the application zip files (the only thing that we have so far). Does that sounds like doable this week? if not I am happy to move forward with this loading bits first and add the ApplicationsService later on.

**Comment by erdemedeiros** [comment]
@salaboy yeah, it makes sense to move it to core common. I'll do that.

Concerning the ApplicationsService I think it just a matter of renaming things: currently I have `ApplicationContent` that can be renamed to `Application` and add the zip folder name to it. And I have `ApplicationLoader` that can be renamed to ApplicationsService.

**Comment by salaboy** [comment]
@erdemedeiros great! please do that renaming

**Pull request merged**
