### PR TITLE
Add jpa feature enable or disable control.

### PR DESCRIPTION
**Pull request by autumind**
Module `activiti-spring-boot-starter-basic`:
Add annotation `@ConditionalOnProperty` to enable or disable JPA feature and enable by default.
The property is associated with `jpaEnabled` in `ActivitiProperties`.

### CODE REVIEW

**Comment by Salaboy** [comment]
@autumind hi there, I notice that you target the PR to a released branch. You should target it to 6.x so it gets merged and included in the next release. 
We are also interested in getting that change in the 7.x, but the starters are now under a different repository called activiti-cloud-starters and the new module is called -configure instead of -basic I will appreciate you sending a PR there as well.

**Comment by autumind** [comment]
@Salaboy Got it, I've changed target to 6.x. This feature is necessary for data access without `JPA`  when using this `-starter`.

**Comment by Salaboy** [comment]
@autumind there will be a release for 6.1, but that's not my responsibility. We are working hard on 7.x stay tuned or joins us if you are interested in this new version. It is a great moment to join the activiti community.

**Comment by autumind** [comment]
@Salaboy Of course I'm interested in that, and I'm glad to be a member of yours. But how can I join you?

**Comment by Salaboy** [comment]
@autumind great stuff.. Join the gitter channel https://gitter.im/Activiti/Activiti7 and we can discuss what kind of things are you interested in contributing to Activiti 7.x. Ping me or @erdemedeiros and @ryandawsonuk

**Comment by Salaboy** [comment]
@balsarori can we review and merge this one for 6.x. In 7 we are taking a different approach for our spring boot starters.

**Pull request closed without merging**
