### PR TITLE
Add HistoricProcessInstanceEntity delete event.

### PR DESCRIPTION
**Pull request by daisuke-yoshimoto**

### CODE REVIEW

**Comment by daisuke-yoshimoto** [comment]
@balsarori
If possible , please feedback.

**Comment by balsarori** [comment]
@daisuke-yoshimoto 
Thanks for the PR. It will be reviewed shortly, we are currently busy with the 6.0 release :)

**Comment by daisuke-yoshimoto** [comment]
@balsarori 
Thank you for your reply.
I see.

**Comment by daisuke-yoshimoto** [comment]
@balsarori
If possible , please feedback.

**Comment by balsarori** [comment]
@daisuke-yoshimoto thanks for the PR.
 
ENTITY_DELETED gets fired when the runtime process instance and task instances are completed/deleted. It will be good if there is another event type to fire when a historic process/task is deleted.

**Comment by daisuke-yoshimoto** [comment]
@balsarori

Thank you  for your reploy.
Should I change to ActivitiEventType.HISTORIC_PROCESS_INSTANCE_ENTITY_DELETED?

**Comment by balsarori** [comment]
@daisuke-yoshimoto I think your original approach is correct can you also do the same for deleting historic task instance?

**Comment by daisuke-yoshimoto** [comment]
@balsarori

I see.
I will add ActivitiEventType.HISTORIC_TASK_INSTANCE_ENTITY_DELETED.

**Comment by balsarori** [comment]
@daisuke-yoshimoto 
Using the ActivitiEventType.ENTITY_DELETED event is fine and makes more sense. No, need to add new event types as I mentioned previously.
Thanks

**Comment by daisuke-yoshimoto** [comment]
@daisuke-yoshimoto

I'm sorry that my understanding was mistaken.
Should I change my pull request to apply my original modifications to historic task instance as well?

**Comment by balsarori** [comment]
Yes, please apply you original modifications to historical task instance as well.

**Comment by daisuke-yoshimoto** [comment]
@balsarori 

Thank you for your reploy.
I added to the historical task instance as well.

It seems there was a terrorist attack in the UK, are you all right?

**Comment by balsarori** [comment]
Thanks for the update 👍 

Too bad what's happening to the world these days. I'm alright thanks!

**Comment by daisuke-yoshimoto** [comment]
@balsarori 

Thank you for merging.
I'm relieved that you are OK.

**Pull request merged**
