### PR TITLE
Bugfix for #865 - Activiti6: Invalid reference in 'bpmnElement' attri…

### PR DESCRIPTION
**Pull request by reva**
Fix for https://github.com/Activiti/Activiti/issues/865

### CODE REVIEW

**Comment by tijsrademakers** [comment]
@reva can you also add a unit test showing the "invalid reference in 'bpmnElement'" issue? Ideally this unit test should use only the default RepositoryService createDeployment logic. So not using BpmnParse directly in the unit test.

**Comment by reva** [comment]
@tijsrademakers The 'issue' that I'm seeing here is really only a logging statement that is not necessary. Beyond that, I don't have any issues. Why not use the BpmnParse directly?

**Comment by tijsrademakers** [comment]
@reva ok, but I still don't understand when this logging statement is shown. So can you add a unit test that would make this logging statement to appear? Using BpmnParse directly is not what most of our community developers will do, so would be better to use the public API service methods.

**Comment by reva** [comment]
@tijsrademakers The logging statement is shown for any process that has any graphical information (di) and flows in it. Anyway, I looked into it and saw that the sequence flows aren't used anywhere. I changed my pull request to remove the map and all logic with it. Feel free to decline this one...

**Comment by tijsrademakers** [comment]
Fixed it by changing the sequence flow lookup code.

**Pull request closed without merging**
