### PR TITLE
ACT-3999: ClassCastException when importing a WSDL

### PR DESCRIPTION
**Pull request by cdeneux**
see https://activiti.atlassian.net/browse/ACT-3999

### CODE REVIEW

**Comment by tijsrademakers** [comment]
Merged manually

**Comment by cdeneux** [comment]
I just tried Activiti 5.18.0 to verify the merge of this pull request in the master branch as mentioned below, but the same error occurs under same conditions.

So, I think a mistake occurs when merging this pull request.
Moreover, I'm not able to retrieve a commit associated to the pull request merge in the master branch.

Can you try to merge again this pull request ?
Thanks

**Comment by jbarrez** [comment]
I cannot find the code in this commit indeed in 5.18 (but i'm on a hotel wifi, so a thorough search is hard). Reopening PR until further notice.

**Comment by tijsrademakers** [comment]
Now it should have been merged correctly

**Comment by cdeneux** [comment]
Thanks Tijs. The merge is ok.
Can you change the fix version of the issue ? It is marked for 5.18.0 but should be 5.19.0.1

**Pull request closed without merging**
