### PR TITLE
Archetypes unittest

### PR DESCRIPTION
**Pull request by smirzai**
This is the first activiti archetype to create a unit test. 
This is going to replace https://github.com/Activiti/activiti-unit-test-template
To create a unit test case with customized package, version and  artifactid. Here is the syntax:

mvn archetype:generate 
    -DarchetypeGroupId=org.activiti.archetypes 
    -DarchetypeArtifactId=activiti-archetype-unittest 
    -DarchetypeVersion=5.17.1-SNAPSHOT 
    -DgroupId=org.myGroup
     -DartifactId=myArtifact

### CODE REVIEW

**Comment by tijsrademakers** [comment]
Thanks Saeid, that's a very nice and handy archetype. Would be great if you could add some documentation as well. And an article is also great, if you don't have time for it we can give it a go as well, just let us know.

**Comment by smirzai** [comment]
Hi Tijs
Sure, I  will do with pleasure. 
Where do you think it should  be documented ? activiti guide ? or a seperate documentation for tooling ?

**Comment by smirzai** [comment]
Here is a post about it my blog.
http://tech.blog.saeidmirzaei.com/?p=306

**Comment by smirzai** [comment]
https://twitter.com/smirzai/status/571997424450994176

**Comment by smirzai** [comment]
@tijsrademakers 
Do you think this should come in Activiti guide ? Or do we need to start a second documentation for tooling ? Or is that blog post enough ?

**Comment by tijsrademakers** [comment]
Yes, would be good to have this in the Activiti user guide.

**Comment by smirzai** [comment]
Hi
The documentation is now available in https://github.com/Activiti/Activiti/pull/699

Could you please check and merge it ?

**Comment by smirzai** [comment]
I checked the standard maven repository. I cannot find archetype there.
Is there any reason for it ? If not what configuration is necessary to make it available in standard maven repositroy ?

**Comment by jbarrez** [comment]
@smirzai : when uploading to maven we do a -Pdistro, so the module should be added here if I'm not mistaken: https://github.com/Activiti/Activiti/blob/master/pom.xml#L907

cc @tijsrademakers

**Comment by smirzai** [comment]
@Jbarez
@tijsrademakers <https://github.com/tijsrademakers>
Would this do the job ?
https://github.com/Activiti/Activiti/pull/726

**Pull request merged**
