### PR TITLE
move propagation to travis 

### PR DESCRIPTION
**Pull request by almerico**

### CODE REVIEW

**Comment by almerico** [comment]
> no binaries please, must be downloaded from somewhere so we can track versions
now it is only for test and we have to discuss where to put it

**Comment by almerico** [comment]
@mteodori clone and build go repo possibly a bad option because of slow build of this repo - since this is service stuff and we are not really interesting in version possibly a good option have some kind of repo with service bina

**Comment by almerico** [comment]
https://github.com/jenkins-x/jx-release-version/releases/tag/v1.0.24
https://repo1.maven.org/maven2/io/jenkins/updatebot/updatebot/1.1.53/updatebot-1.1.53.jar

**Comment by mteodori** [comment]
> @mteodori clone and build go repo possibly a bad option because of slow build of this repo - since this is service stuff and we are not really interesting in version possibly a good option have a repo with service binaries

we can add to cache to do it just once, I install jx-release-version with:
```
go get github.com/jenkins-x/jx-release-version
~/go/bin/jx-release-version
```

wasn't the other option to just call the dependabot API workable?

**Comment by almerico** [comment]
as far as I remember there is an issue with version naming for use dependabot in version 7 or something is changed?

**Comment by almerico** [comment]
binaries removed  can you please review @mteodori

**Comment by almerico** [comment]
@mteodori cache added

**Pull request merged**
